using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

var inputPath = args.Length > 0 ? args[0] : "specs/tripletex-openapi-original.json";
var outputPath = args.Length > 1 ? args[1] : "specs/tripletex-openapi-processed.json";
var mappingsPath = args.Length > 2 ? args[2] : "src/Tripletex.Api/Generated/PathMappings.g.cs";

if (!File.Exists(inputPath))
{
    Console.Error.WriteLine($"Input file not found: {inputPath}");
    Console.Error.WriteLine("Downloading from Tripletex...");

    using var httpClient = new HttpClient();
    var specJson = await httpClient.GetStringAsync("https://tripletex.no/v2/openapi.json");
    EnsureDirectoryExists(inputPath);
    await File.WriteAllTextAsync(inputPath, specJson);
    Console.WriteLine($"Downloaded spec to {inputPath}");
}

Console.WriteLine($"Processing {inputPath}...");

var json = await File.ReadAllTextAsync(inputPath);
var doc = JsonNode.Parse(json) ?? throw new InvalidOperationException("Failed to parse OpenAPI spec");

var paths = doc["paths"]?.AsObject();
if (paths is null)
{
    Console.Error.WriteLine("No paths found in spec");
    return 1;
}

var mappings = new Dictionary<string, string>();
var pathsToRename = new List<(string original, string sanitized)>();

foreach (var (path, _) in paths)
{
    var sanitized = SanitizePath(path, mappings);
    if (sanitized != path)
        pathsToRename.Add((path, sanitized));
}

foreach (var (original, sanitized) in pathsToRename)
{
    var value = paths[original];
    paths.Remove(original);
    paths[sanitized] = value!.DeepClone();
}

EnsureDirectoryExists(outputPath);
var options = new JsonSerializerOptions { WriteIndented = true };
await File.WriteAllTextAsync(outputPath, doc.ToJsonString(options));
Console.WriteLine($"Wrote processed spec to {outputPath} ({paths.Count} paths)");

EnsureDirectoryExists(mappingsPath);
await GenerateMappingsFile(mappingsPath, mappings);
Console.WriteLine($"Wrote {mappings.Count} path mappings to {mappingsPath}");

return 0;

static void EnsureDirectoryExists(string filePath)
{
    var dir = Path.GetDirectoryName(filePath);
    if (!string.IsNullOrEmpty(dir))
        Directory.CreateDirectory(dir);
}

static string SanitizePath(string path, Dictionary<string, string> mappings)
{
    var result = path;

    // Handle :action patterns (e.g., /:approve → /approve)
    result = Regex.Replace(result, @"/:(\w+)", m =>
    {
        var action = m.Groups[1].Value;
        var sanitized = $"/{action}";
        var original = m.Value;
        mappings.TryAdd(sanitized, original);
        return sanitized;
    });

    // Handle >summary patterns (e.g., />last → /last)
    result = Regex.Replace(result, @"/>(\w+)", m =>
    {
        var name = m.Groups[1].Value;
        var sanitized = $"/{name}";
        var original = m.Value;
        mappings.TryAdd(sanitized, original);
        return sanitized;
    });

    // Handle mid-segment colons (e.g., unmatched:csv → unmatchedCsv)
    result = Regex.Replace(result, @"(\w+):(\w)", m =>
    {
        var before = m.Groups[1].Value;
        var after = m.Groups[2].Value;
        var sanitized = before + char.ToUpperInvariant(after[0]) + after[1..];
        var original = m.Value;

        if (sanitized != original)
            mappings.TryAdd(sanitized, original);

        return sanitized;
    });

    return result;
}

static async Task GenerateMappingsFile(string path, Dictionary<string, string> mappings)
{
    var lines = new List<string>
    {
        "// <auto-generated>",
        "// Generated by Tripletex.SpecPreprocessor",
        "// </auto-generated>",
        "",
        "namespace Tripletex.Api.Generated;",
        "",
        "internal static class GeneratedPathMappings",
        "{",
        "    public static readonly IReadOnlyDictionary<string, string> Mappings = new Dictionary<string, string>",
        "    {"
    };

    foreach (var (sanitized, original) in mappings.OrderBy(m => m.Key))
    {
        lines.Add($"        [\"{Escape(sanitized)}\"] = \"{Escape(original)}\",");
    }

    lines.Add("    };");
    lines.Add("}");

    await File.WriteAllTextAsync(path, string.Join(Environment.NewLine, lines));

    static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
